public class Constants {
    
    public static final String ERROR_AGE = 'Not suitable for age.';
    public static final String ERROR_DATE = 'Already flew away.';
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String FLIGHT_STATUS_ACCEPTED = 'Accepted';
    public static final String FLIGHT_STATUS_OFFER_PENDING = 'Offer Pending';
    public static final String FLIGHT_STATUS_OFFER_REQUESTED = 'Requested';
    public static final String EXECEPTION_TEXT = 'The following exception has occurred: ';
    public static final String EXECEPTION_DML = 'DmlException caught.';
    public static final String EXECEPTION_QUERY = 'QueryException caught.';
    public static final String EXECEPTION_GENERAL = 'Exception caught.';
    public static final Integer FLIGHT_CLEANER_DAYS = 30;
    public static final String EMAIL_SUBJECT_FLIGHT_CLEANER = 'Flight cleaner Batch';
    public static final String CUSTOM_METADATA_TYPE_NAME = 'Send_Email__mdt';
    public static final String RESPONSE_BODY_TOURIST_NAME_EMPTY = 'The name must be not empty.';
    public static final String RESPONSE_BODY_TOURIST_AGE_NOT_NUMBER = 'The age must be a number.';
    public static final String DUPLICATE = 'Duplicate.';
    public static final String REQUEST_HEADER_RAPIDAPI_KEY_TEXT = 'x-rapidapi-key';
    public static final String REQUEST_HEADER_RAPIDAPI_KEY = 'dbba4ce498msh0a2aa20f5b276eep1affd2jsn972508114931';
    public static final String REQUEST_HEADER_RAPIDAPI_HOST_TEXT = 'x-rapidapi-host';
    public static final String REQUEST_HEADER_RAPIDAPI_HOST = 'weatherbit-v1-mashape.p.rapidapi.com';
    public static final String METHOD_HTTP_GET = 'GET';
    public static final String METHOD_HTTP_POST = 'POST';
    public static final Integer RESPONSE_STATUS_CODE_404 = 404;
    public static final Integer RESPONSE_STATUS_CODE_200 = 200;
    public static final Integer RESPONSE_STATUS_CODE_409 = 409;
    public static final String ERROR = 'Error';
    public static final String TOURIST_ASSIGNMENT_ERROR_MSG_GENERAL = System.Label.TouristAssignmentErrorMsgGeneral;
}